### ISSUE TITLE
Manage nullable object HasValue query

### ISSUE THREAD

**Issue by HisCodeness** [mathieumack/Linq2CouchBaseLiteExpression#8]
Be able to query : (e) => e.Birthday.HasValue

**Comment by mathieumack** [comment]
I've done this check in the PR #9 
You can check alpha nuget published package.

**Comment by mathieumack** [comment]
Note : The field must exists in the document.
Ex : (e) => !e.Birthday.HasValue will return 0 even if you have documents without a "Birthday" field.
